### ISSUE TITLE
Getting frontend compilation error with webpack

### ISSUE THREAD

**Issue by Dudeplayz** [anezthes/carbon-vaadin14#2]
I am getting the following error, when I try to use the carbon theme.

```log
2022-10-14 10:00:57 [dev-server-output] INFO  DevServerOutputTracker - WARNING in InjectManifest has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.
2022-10-14 10:00:57 [dev-server-output] INFO  DevServerOutputTracker - 
2022-10-14 10:00:57 [dev-server-output] INFO  DevServerOutputTracker - ERROR in ../target/flow-frontend/themes/carbon/styles.css?inline
2022-10-14 10:00:57 [dev-server-output] INFO  DevServerOutputTracker - Module build failed (from ../node_modules/css-loader/dist/cjs.js):
2022-10-14 10:00:57 [dev-server-output] INFO  DevServerOutputTracker - Error: Can't resolve 'line-awesome/dist/line-awesome/css/line-awesome.min.css' in '/Users/dario/DEV/IdeaProjects/lisy/ui/target/flow-frontend/themes/carbon'
2022-10-14 10:00:57 [dev-server-output] INFO  DevServerOutputTracker -     at /Users/dario/DEV/IdeaProjects/lisy/ui/node_modules/enhanced-resolve/lib/Resolver.js:209:21
2022-10-14 10:00:57 [dev-server-output] INFO  DevServerOutputTracker -     at /Users/dario/DEV/IdeaProjects/lisy/ui/node_modules/enhanced-resolve/lib/Resolver.js:285:5
2022-10-14 10:00:57 [dev-server-output] INFO  DevServerOutputTracker -     at eval (eval at create (/Users/dario/DEV/IdeaProjects/lisy/ui/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
2022-10-14 10:00:57 [dev-server-output] INFO  DevServerOutputTracker -     at /Users/dario/DEV/IdeaProjects/lisy/ui/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
2022-10-14 10:00:57 [dev-server-output] INFO  DevServerOutputTracker -     at /Users/dario/DEV/IdeaProjects/lisy/ui/node_modules/enhanced-resolve/lib/Resolver.js:285:5
2022-10-14 10:00:57 [dev-server-output] INFO  DevServerOutputTracker -     at eval (eval at create (/Users/dario/DEV/IdeaProjects/lisy/ui/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
2022-10-14 10:00:57 [dev-server-output] INFO  DevServerOutputTracker -     at /Users/dario/DEV/IdeaProjects/lisy/ui/node_modules/enhanced-resolve/lib/Resolver.js:285:5
2022-10-14 10:00:57 [dev-server-output] INFO  DevServerOutputTracker -     at eval (eval at create (/Users/dario/DEV/IdeaProjects/lisy/ui/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
2022-10-14 10:00:57 [dev-server-output] INFO  DevServerOutputTracker -     at /Users/dario/DEV/IdeaProjects/lisy/ui/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
2022-10-14 10:00:57 [dev-server-output] INFO  DevServerOutputTracker -     at /Users/dario/DEV/IdeaProjects/lisy/ui/node_modules/enhanced-resolve/lib/Resolver.js:285:5
2022-10-14 10:00:57 [dev-server-output] INFO  DevServerOutputTracker - [build-status] 1 error and 1 warning were reported.
2022-10-14 10:00:57 [dev-server-output] INFO  DevServerOutputTracker - [build-status] : Failed to compile.
```

**Comment by anezthes** [comment]
@Dudeplayz should be fixed now thanks to @juuso-vaadin.
