### ISSUE TITLE
addon: Failed to run the test app

### ISSUE THREAD

**Issue by mvysny** [anezthes/carbon-vaadin14#4]
I've tried to run the addon via the test app (running `src/test/java/.../Application.java`), unfortunately it fails with:

```
Caused by: java.io.FileNotFoundException: Could not find the downloaded Node.js binary in /home/mavi/.vaadin/node/tmp/node-v16.15.0-linux-x64/bin/node
	at com.vaadin.flow.server.frontend.installer.NodeInstaller.installNodeUnix(NodeInstaller.java:285) ~[flow-server-23.1.1.jar:23.1.1]
	at com.vaadin.flow.server.frontend.installer.NodeInstaller.installNode(NodeInstaller.java:267) ~[flow-server-23.1.1.jar:23.1.1]
```
Indeed, there's corepack, npm and npx but no node binary. A glitch in older Vaadin perhaps? Perhaps we should upgrade Vaadin version in the addon.

**Comment by mvysny** [comment]
Nope, upgrading to Vaadin 23.3.12 just always returns 404. I wonder whether the test classpath is not scanned for views?
